#version: '3.8'
#
#services:
#  mongodb:
#    image: mongo:latest
#    ports:
#      - "27017:27017"
#    volumes:
#      - mongodb_data:/data/db
#
#  chat:
#    build:
#      context: .
#      dockerfile: Dockerfile
#    ports:
#      - "8080:8080"
#    depends_on:
#      - mongodb
#
#volumes:
#  mongodb_data:
#    
version: "3.8"

services:
  mongodb:
    container_name: mongodb
    image: mongo:latest
    networks:
      chat:
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
#  chat:
#    build:
#      context: .
#      dockerfile: Dockerfile
#    ports:
#      - "8080:8080"
#    depends_on:
#      - mongodb
#    networks:
#      chat:
#    restart: on-failure

networks:
  chat:

volumes:
  mongodb_data: